"""initial migration

Revision ID: 3423c3482291
Revises: 472e1c3f94f8
Create Date: 2017-05-25 15:30:10.393000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3423c3482291'
down_revision = '472e1c3f94f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_auth', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('menu_auth', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'users', 'users_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('menu_auth', 'update_time')
    op.drop_column('menu_auth', 'create_time')
    # ### end Alembic commands ###
