"""add user is_manage

Revision ID: 3e9b7f664aa3
Revises: e62ec86d6085
Create Date: 2017-05-26 15:36:54.714000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e9b7f664aa3'
down_revision = 'e62ec86d6085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'users_group', ['group_id'], ['id'])
    op.drop_column('users', 'is_manage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_manage', mysql.ENUM(u'1', u'0'), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
