"""del status and role

Revision ID: 3ea73f4b6c4b
Revises: 6e5c97b74838
Create Date: 2017-05-12 10:41:08.436000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ea73f4b6c4b'
down_revision = '6e5c97b74838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kerry', 'status')
    op.drop_column('kerry', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kerry', sa.Column('role', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('kerry', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
