"""initial migration

Revision ID: 472e1c3f94f8
Revises: fe35ef6f0de6
Create Date: 2017-05-25 14:03:20.346000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '472e1c3f94f8'
down_revision = 'fe35ef6f0de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_auth', sa.Column('grant', sa.String(length=100), nullable=True))
    op.drop_column('menu_auth', 'controller')
    op.create_foreign_key(None, 'users', 'users_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.add_column('menu_auth', sa.Column('controller', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('menu_auth', 'grant')
    # ### end Alembic commands ###
