"""migration

Revision ID: c83b808fab81
Revises: e9cd344e0e3d
Create Date: 2017-05-19 15:14:40.716000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c83b808fab81'
down_revision = 'e9cd344e0e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_group', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('users_group', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.drop_column('users_group', 'create_timestamp')
    op.drop_column('users_group', 'update_timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_group', sa.Column('update_timestamp', mysql.TIMESTAMP(), nullable=True))
    op.add_column('users_group', sa.Column('create_timestamp', mysql.TIMESTAMP(), nullable=True))
    op.drop_column('users_group', 'update_time')
    op.drop_column('users_group', 'create_time')
    # ### end Alembic commands ###
