"""initial migration

Revision ID: fe35ef6f0de6
Revises: d0f50996aa77
Create Date: 2017-05-22 17:36:57.472000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe35ef6f0de6'
down_revision = 'd0f50996aa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('controller', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'users', 'users_group', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_table('menu_auth')
    # ### end Alembic commands ###
